#version 430 core

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D ImageOut;

uniform int WIDTH;
uniform int HEIGHT;
uniform mat4 invProjection;
uniform mat4 invView;
uniform vec3 CameraPos;
uniform float Smoothness;

const float infinity = 1.0 / 0.0;
const float pi = 3.1415926535897932385;
const float tau = 6.2831853071795864769;
const float EPSILON = 0.001;

ivec2 PixelCoords = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);

float smin(float a, float b, float k, out float hOutput) {
    float h = clamp(0.5 + 0.5 * (a - b) / k, 0.0, 1.0);
    hOutput = h;
    return mix(a, b, h) - k * h * (1.0 - h);
}

struct Ray {
    vec3 Origin;
    vec3 Direction;
};

vec3 RayAt(inout Ray ray, float t) {
    return ray.Origin + ray.Direction * vec3(t);
}

struct SDFObject {
    vec4 Position;
    float Radius;
    int ObjectType;
    float padding0;
    vec4 Albedo;
};

layout(std430, binding = 0) readonly buffer Objects {
    SDFObject SDFObjects[];
};

uniform int SDFObjectsSize;

float SDFSphereDistance(SDFObject object, Ray ray) {
    return distance(ray.Origin, object.Position.xyz) - object.Radius;
}

float GetSDFDistance(SDFObject object, Ray ray) {
    if (object.ObjectType == 1)
        return SDFSphereDistance(object, ray);
    else return 0;
}

vec3 RayColour(Ray ray) {
    const int MaxDepth = 500;
    for (int i = 0; i < MaxDepth; i++) {
        vec3 ObjectAlbedo = vec3(0.0);
        float t = infinity;

        for (int j = 0; j < SDFObjectsSize; j++) {
            SDFObject CurrObject = SDFObjects[j];
            //eladesceelasobenobaileevanwashere
            float tCandidate = GetSDFDistance(CurrObject, ray);

            float h = 0.0;

            t = (j == 0) ? tCandidate : smin(t, tCandidate, Smoothness, h);

            ObjectAlbedo = (j == 0) ? CurrObject.Albedo.rgb : mix(ObjectAlbedo, CurrObject.Albedo.rgb, h);
        }

        ray.Origin = RayAt(ray, t);

        if (t < EPSILON) {
            //vec3 Normal = normalize(ray.Origin - CollidedObject.Position.xyz);
            //vec3 SkyDir = vec3(0.0, 1.0, 0.0);

            //vec3 Diffuse = max(vec3(dot(SkyDir, Normal)), 0.0) * ObjectAlbedo;
            vec3 Ambient = 0.5 * ObjectAlbedo;

            vec3 FinalColour = Ambient;

            return FinalColour;
        }
    }
    return vec3(0.0);
}

Ray getRay(vec2 pixelCoords) {
    vec4 NDCoords = vec4((pixelCoords + 0.5) / vec2(WIDTH, HEIGHT) * 2 - 1.0, -1.0, 1.0);

    vec4 Result = invProjection * NDCoords;
    Result = vec4(Result.xyz / Result.w, 1.0);

    Result = normalize(invView * vec4(Result.xyz, 0.0));

    Ray ray;
    ray.Origin = CameraPos;
    ray.Direction = vec3(Result.xyz);

    return ray;
}

void main () {
    Ray origRay = getRay(PixelCoords);
    vec3 FinalColour = RayColour(origRay);
    imageStore(ImageOut, PixelCoords, vec4(FinalColour, 1.0));
}